#if !canImport(ObjectiveC)
import XCTest

extension OperationQueueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OperationQueueTests = [
        ("testCurrentQueue", testCurrentQueue),
        ("testCurrentQueueOnMain", testCurrentQueueOnMain),
        ("testDeinitializationWhenAllOperationsHaveCompleted", testDeinitializationWhenAllOperationsHaveCompleted),
        ("testLifetimeWhileOperationsAreRunning", testLifetimeWhileOperationsAreRunning),
    ]
}

extension OperationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OperationTests = [
        ("testDescription", testDescription),
        ("testSimpleExecution", testSimpleExecution),
        ("testWaitingForDependencies", testWaitingForDependencies),
        ("testWaitingForDependenciesWhichAreCancelled", testWaitingForDependenciesWhichAreCancelled),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OperationQueueTests.__allTests__OperationQueueTests),
        testCase(OperationTests.__allTests__OperationTests),
    ]
}
#endif
