#if !canImport(ObjectiveC)
import XCTest

extension GCDOperationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GCDOperationsTests = [
        ("testMutuallyExclusiveCondition", testMutuallyExclusiveCondition),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GCDOperationsTests.__allTests__GCDOperationsTests),
    ]
}
#endif
