#if !canImport(ObjectiveC)
import XCTest

extension MutuallyExclusiveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MutuallyExclusiveTests = [
        ("testMutuallyExclusiveCondition", testMutuallyExclusiveCondition),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MutuallyExclusiveTests.__allTests__MutuallyExclusiveTests),
    ]
}
#endif
